# Generated by Django 4.1.7 on 2023-03-30 16:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('customer', '0005_shippingaddress_payment'),
    ]

    operations = [
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('review', models.CharField(max_length=100)),
                ('date', models.DateField(auto_now_add=True)),
                ('rating', models.FloatField()),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='revie_product', to='customer.product')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='revie_user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
