# Generated by Django 4.1.7 on 2023-03-14 03:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='custuser',
            name='address',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='custuser',
            name='phone',
            field=models.IntegerField(null=True),
        ),
    ]
